sudo: false

language: node_js

dist: jammy

node_js:
  - "20.8.0"
  - "stable"

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - corepack enable
  - yarn set version 3.6.4

install:
  - yarn install --immutable

script:
  - "npm test"

matrix:
  allow_failures:
    - node_js: "stable"
