os: linux
dist: jammy
language: node_js

node_js:
  - "20.8.0"

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - google-chrome-stable --headless --remote-debugging-port=9220 http://localhost
  - corepack enable
  - yarn set version 3.6.4

install:
  - yarn install --immutable

script:
  - "npm test"
