os: linux
dist: jammy
language: node_js

node_js:
  - "20.8.0"

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - google-chrome-stable --headless --no-sandbox --ignore-gpu-blocklist --remote-debugging-port=9222 http://localhost &
  - corepack enable
  - yarn set version 3.6.4

install:
  - yarn install --immutable

script:
  - "npm test"
