#!/bin/bash

if [ -z "$1" ]; then
    echo ""
    echo "You forgot to enter the branch on the command line!"
    echo ""
    exit
else
    FILE="$1"
    CSS=".css"
    JS=".js"
    HTML=".html"
    cp ../css/tideline.css example/$FILE$CSS
    cp ../example/bundle.js example/$FILE$JS
    cp ../example/data/device-data.json example/
    cp ../example/index.html example/$FILE$HTML

    python properly_link_html.py $FILE
fi