#!/bin/bash

FILE="$1"
HTML=".html"
cp ../css/tideline.css css/
cp ../example/bundle.js example/
cp ../example/data/device-data.json example/
cp ../example/example.css example/
cp ../example/index.html example/$FILE$HTML